#testing with venv in py27

test_py27:
  script:
  - pwd
  - virtualenv _venv27 --python=python2
  - source _venv27/bin/activate
  - echo $VIRTUAL_ENV
  - pip install -U --force pip
  - pip install -r requirements.txt -U -q
  - pytest kechain2
  tags:
  - python27

# testing with venv in py35

test_py35:
  script:
  - pwd
  - virtualenv _venv35 --python=python3
  - source _venv35/bin/activate
  - echo $VIRTUAL_ENV
  - pip install -U --force pip
  - pip install -r requirements.txt -U -q
  - pytest kechain2
  tags:
  - python35

after_script:
- rm -rf _venv*


# Test in python 3.5 using a Docker runner
#test_35:
#  image: python:3.5
#  script:
#  - pip install -U --force pip
#  - pip install -r requirements-testing.txt -U
#  - pytest kechain2
#  after_script:
#  - echo "cleanup docker here"
