before_script:
  - pip install tox
  - sudo pip install pip wheel -U --force


test_py27:
  variables:
    TOXENV: py27
  script:
    - tox

test_py34:
  variables:
    TOXENV: py34
  script:
    - tox

