sudo: false
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

matrix:
  include:
    - env: TOXENV=stats
      python: 3.6

install:
  pip install tox-travis coveralls

script: tox

notifications:
  email: false

after_success:
  coveralls
