sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

#env:
#  - TOXENV=py27
#  - TOXENV=py34
#  - TOXENV=py35

install: pip install tox-travis

script: tox

notifications:
  email: false