name: Release pykechain

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    - name: Sync dependencies for build
      run: |
        uv sync
    - name: Build
      run: |
        uv build
    - name: Publish to PyPI
      env:
        UV_PYPI_TOKEN: ${{ secrets.PYPI_PYKECHAIN_TOKEN }}
      run: |
        uv publish
